// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1i5xAoRwVtCqaK5o383e6zouEJEsfOiM',
    appId: '1:332254951499:web:d59ee731ac03da702635ce',
    messagingSenderId: '332254951499',
    projectId: 'flutter-instagram-b78eb',
    authDomain: 'flutter-instagram-b78eb.firebaseapp.com',
    storageBucket: 'flutter-instagram-b78eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCChC-HpYYib5506c9afeuWf64qJnit3CA',
    appId: '1:332254951499:android:d7a8375ad61c7d1c2635ce',
    messagingSenderId: '332254951499',
    projectId: 'flutter-instagram-b78eb',
    storageBucket: 'flutter-instagram-b78eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtahaCQfQIwOgpK49k9ODuU3BjHIy3lbs',
    appId: '1:332254951499:ios:f60554e3c95453b02635ce',
    messagingSenderId: '332254951499',
    projectId: 'flutter-instagram-b78eb',
    storageBucket: 'flutter-instagram-b78eb.appspot.com',
    iosClientId: '332254951499-c3ti7v3pfts0gk6cm35r1bcjmqd7vbjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtahaCQfQIwOgpK49k9ODuU3BjHIy3lbs',
    appId: '1:332254951499:ios:f60554e3c95453b02635ce',
    messagingSenderId: '332254951499',
    projectId: 'flutter-instagram-b78eb',
    storageBucket: 'flutter-instagram-b78eb.appspot.com',
    iosClientId: '332254951499-c3ti7v3pfts0gk6cm35r1bcjmqd7vbjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstagram',
  );
}
